[package]
name = "leviathan_v2"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-primitives = {version = "1.5.7", features = ["serde", "rlp"]}
alloy-sol-types = "1.5.7"
secp256k1 = {version = "0.31.1", features = ["recovery"]}
sha3 = "0.10.8"
sha2 = {version = "0.10.8", features = ["oid"]}
ripemd = "0.1.3" 
bytes = "1.11.1"
alloy-rlp = "0.3.15"
serde = {version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
stacker = "0.1.23"
tracing = "0.1.44"
tracing-subscriber = {version = "0.3.23", features = ["env-filter"]}
num-bigint = "0.4.6"
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
ark-ec = "0.5.0"
eth_trie = "0.6.1"
rsa = "0.9.10"
rand = "0.8.5"
ark-groth16 = "0.5.0"
ark-snark = "0.5.0"
ark-serialize = "0.5.0"
light-poseidon = "0.4.0"
# Cargo.toml に追記
ark-circom = { version = "0.5.0-alpha" }
tendermint-abci = "0.40.4"
tendermint-proto = "0.40.4"
rocksdb = "0.24.0"
tempfile = "3.27.0"
jsonrpsee = { version = "0.26.0", features = ["server", "macros"] }
async-trait = "0.1.89"
tokio = { version = "1.52.1", features = ["full"] }
tendermint-rpc = { version = "0.40.4", features = ["http-client"] }
alloy-consensus = "2.0.4"
alloy-rpc-types = "2.0.4"
lru = "0.18.0"
# RPCリクエストのロギング用
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "trace"] }
http = "1.4.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }

clap = { version = "4.5", features = ["derive"] }
